version: "3.8" 
services:
  php:
    build:
      context: .
    image: autodoc
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/" 
    command: php -S 0.0.0.0:9000 -t public/